<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime" />
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.HighDefinition.Runtime">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.RenderPipelines.HighDefinition.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Il2CppSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Rewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="modio.UnityPlugin">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\modio.UnityPlugin.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="AeLa.EasyFeedback">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\AeLa.EasyFeedback.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="Whinarn.UnityMeshSimplifier.Runtime">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Whinarn.UnityMeshSimplifier.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\AppData\Roaming\com.kesomannen.gale\shadows-of-doubt\profiles\Default\BepInEx\interop\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common" />
  </ItemGroup>
</Project>