using System;
using Steamworks;

namespace SoDCoop.Network.Steam;

/// <summary>
/// Wires up every Steam callback the mod cares about. Goes through
/// <see cref="NativeCallbackRegistry"/> rather than Steamworks.NET's
/// <c>Callback&lt;T&gt;.Create</c> — the latter is unusable under IL2CPP
/// because the generic <c>DispatchDelegate</c> constructor has no AOT
/// code generated by the game build.
///
/// <para>SoD's own <c>SteamAPIController</c> already calls
/// <c>SteamAPI.Init()</c> at game launch — we never call it again. We only
/// register callbacks and call <see cref="SteamAPI.RunCallbacks"/> from the
/// mod's per-frame tick.</para>
/// </summary>
public static class SteamCallbacks
{
    private static bool _initialized;
    /// <summary>One-shot guard — set on first call regardless of outcome so we
    /// don't spam the log every tick when registration fails.</summary>
    private static bool _attempted;

    // Native callback handles. Held so we can unregister on shutdown.
    private static IntPtr _hLobbyCreated;
    private static IntPtr _hLobbyEnter;
    private static IntPtr _hLobbyChatUpdate;
    private static IntPtr _hLobbyDataUpdate;
    private static IntPtr _hGameLobbyJoinRequested;
    private static IntPtr _hConnStatusChanged;

    public static void Initialize()
    {
        if (_attempted) return;
        _attempted = true;

        try
        {
            if (!SteamAPI.IsSteamRunning())
            {
                Plugin.Log.LogError("[SteamCallbacks] SteamAPI is not running — Steam P2P unavailable. Did the game launch outside Steam?");
                return;
            }

            int registered = 0;
            registered += TryRegister<LobbyCreated_t>            (LobbyCreated_t.k_iCallback,            SteamLobby.OnLobbyCreated,            out _hLobbyCreated,           "LobbyCreated");
            registered += TryRegister<LobbyEnter_t>              (LobbyEnter_t.k_iCallback,              SteamLobby.OnLobbyEnter,              out _hLobbyEnter,             "LobbyEnter");
            registered += TryRegister<LobbyChatUpdate_t>         (LobbyChatUpdate_t.k_iCallback,         SteamLobby.OnLobbyChatUpdate,         out _hLobbyChatUpdate,        "LobbyChatUpdate");
            registered += TryRegister<LobbyDataUpdate_t>         (LobbyDataUpdate_t.k_iCallback,         SteamLobby.OnLobbyDataUpdate,         out _hLobbyDataUpdate,        "LobbyDataUpdate");
            registered += TryRegister<GameLobbyJoinRequested_t>  (GameLobbyJoinRequested_t.k_iCallback,  SteamLobby.OnGameLobbyJoinRequested,  out _hGameLobbyJoinRequested, "GameLobbyJoinRequested");
            // Conn-status callback — under IL2Cpp interop the shim type isn't
            // marshalable (Marshal.PtrToStructure refuses), so we register
            // through RegisterRaw and decode the few fields we need from the
            // native byte buffer at hand-computed offsets.
            registered += TryRegisterConnStatus();

            if (registered == 0)
            {
                Plugin.Log.LogError("[SteamCallbacks] no callbacks could be registered — Steam P2P inactive.");
                return;
            }

            _initialized = true;
            // Avoid SteamUser.GetSteamID() / SteamUtils.GetAppID() in this log
            // line — those go through the IL2CPP-converted Steamworks.NET
            // wrapper which throws "Steamworks is not initialized" because its
            // managed CallbackDispatcher isn't usable under IL2CPP.
            Plugin.Log.LogInfo($"[SteamCallbacks] init complete ({registered}/6 callbacks live, native registry).");

            // ── Steam Datagram Relay bootstrap ───────────────────────────────
            // SDR is the network fabric Steam uses for P2P NAT-traversal.
            // CreateListenSocketP2P returns a valid handle even before SDR is
            // ready, but inbound connections silently won't be delivered until
            // the relay tickets have been fetched. Without it, host's
            // SteamNetConnectionStatusChanged callback never fires for incoming
            // dials — the C++ side never sees them.
            //
            // The managed wrapper SteamNetworkingUtils.InitRelayNetworkAccess()
            // throws "Steamworks is not initialized" under IL2CPP for the same
            // reason SteamUser.GetSteamID() does — its CallbackDispatcher is
            // never bootstrapped in the IL2Cpp-converted Steamworks.NET assembly.
            // Bypass via direct flat-C P/Invoke into steam_api64.dll.
            bool sdrInitOk = NativeCallbackRegistry.InitRelayNetworkAccess();
            Plugin.Log.LogInfo($"[SteamCallbacks] InitRelayNetworkAccess (native): {(sdrInitOk ? "ok" : "failed (SDR will auto-init via first sockets call)")}.");

            // Authentication cert request happens lazily on first Steam-host
            // attempt — calling it here at plugin-load time runs before Steam
            // is fully initialized, returns null, and the resulting per-frame
            // probe spams "could not resolve" warnings into the log. Defer.

            _sdrCheckCountdown = 0; // probe immediately on next RunCallbacks tick
        }
        catch (Exception ex)
        {
            Plugin.Log.LogError($"[SteamCallbacks] init failed: {ex}");
        }
    }

    /// <summary>Pump per frame from <c>NetworkManager.Update()</c>. Drives the
    /// Steam callback queue so all the registered handlers actually fire.
    ///
    /// <para>Uses the native <c>SteamAPI_RunCallbacks</c> P/Invoke instead of
    /// Steamworks.NET's <c>SteamAPI.RunCallbacks()</c> wrapper — the C# wrapper
    /// dispatches through a managed <c>CallbackDispatcher</c> that throws
    /// <c>"Callback dispatcher is not initialized"</c> under IL2CPP, blocking
    /// the underlying native pump from ever running. We don't use the managed
    /// dispatcher anyway; our callbacks come in via native vtable.</para></summary>
    public static void RunCallbacks()
    {
        if (!_initialized) return;
        NativeCallbackRegistry.RunCallbacks();
        // Interface-level pump for SteamNetworkingSockets — services SDR
        // rendezvous packets that the global SteamAPI_RunCallbacks doesn't
        // touch. Without this, accepted connections enter FindingRoute and
        // then time out.
        SteamSocketsNative.RunInterfaceCallbacks();
        PollRelayNetworkStatus();
    }

    // ── SDR status polling ──────────────────────────────────────────────
    // GetRelayNetworkStatus returns the current state of relay token
    // acquisition. We poll once per second until we see a meaningful state
    // change (not Unknown / Attempting), then stop. The state value tells us
    // if listen sockets can actually receive routed inbound connections.
    private static int _sdrCheckCountdown = -1;     // frames until next check (very rough)
    private static int _sdrLastReportedState = -999;
    private static int _sdrLastReportedAuthState = -999;
    private static int _sdrChecks = 0;

    private static void PollRelayNetworkStatus()
    {
        // Disabled (only re-enabled by Initialize success).
        if (_sdrCheckCountdown < 0) return;
        // Roughly once per ~half-second of game ticks. NetworkManager pumps us
        // every Update; assume ~60 fps; 30 ticks ≈ 0.5s.
        if (--_sdrCheckCountdown > 0) return;
        _sdrCheckCountdown = 30;

        try
        {
            int rc = NativeCallbackRegistry.GetRelayNetworkStatus(
                out int eAvail, out int eAvailNetwork, out int eAvailAnyRelay, out string debugMsg);
            if (eAvail != _sdrLastReportedState || (_sdrChecks % 20) == 0)
            {
                _sdrLastReportedState = eAvail;
                Plugin.Log.LogInfo(
                    $"[SDR] avail={(ESteamNetworkingAvailability)eAvail} (rc={rc}) " +
                    $"network={(ESteamNetworkingAvailability)eAvailNetwork} " +
                    $"anyrelay={(ESteamNetworkingAvailability)eAvailAnyRelay} " +
                    $"msg='{debugMsg}'");
            }
            _sdrChecks++;

            // Auth status separately — even if SDR Current, route-finding
            // can still fail without an issued auth cert.
            int authAvail = SteamSocketsNative.GetAuthenticationStatus(out string authMsg);
            if (authAvail != _sdrLastReportedAuthState || (_sdrChecks % 20) == 0)
            {
                _sdrLastReportedAuthState = authAvail;
                Plugin.Log.LogInfo($"[SDR-Auth] avail={(ESteamNetworkingAvailability)authAvail} msg='{authMsg}'");
            }

            // Once we've seen a stable Current state for a few ticks, stop
            // polling so we don't spam the log.
            if (eAvail == (int)ESteamNetworkingAvailability.k_ESteamNetworkingAvailability_Current
                && authAvail == (int)ESteamNetworkingAvailability.k_ESteamNetworkingAvailability_Current
                && _sdrChecks > 4)
            {
                Plugin.Log.LogInfo("[SDR] relay tickets + auth cert ready — disabling status polling.");
                _sdrCheckCountdown = -1;
            }
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"[SDR] GetRelayNetworkStatus: {ex.GetType().Name}: {ex.Message}");
            _sdrCheckCountdown = -1;
        }
    }

    /// <summary>Unregister every callback + free unmanaged memory. Call when
    /// the plugin is shutting down so Steam doesn't keep firing into freed
    /// memory.</summary>
    public static void Shutdown()
    {
        try
        {
            NativeCallbackRegistry.Unregister(_hLobbyCreated);           _hLobbyCreated           = IntPtr.Zero;
            NativeCallbackRegistry.Unregister(_hLobbyEnter);             _hLobbyEnter             = IntPtr.Zero;
            NativeCallbackRegistry.Unregister(_hLobbyChatUpdate);        _hLobbyChatUpdate        = IntPtr.Zero;
            NativeCallbackRegistry.Unregister(_hLobbyDataUpdate);        _hLobbyDataUpdate        = IntPtr.Zero;
            NativeCallbackRegistry.Unregister(_hGameLobbyJoinRequested); _hGameLobbyJoinRequested = IntPtr.Zero;
            NativeCallbackRegistry.Unregister(_hConnStatusChanged);      _hConnStatusChanged      = IntPtr.Zero;
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"[SteamCallbacks] Shutdown: {ex.Message}");
        }
        _initialized = false;
        // Don't reset _attempted — re-trying inside the same process would
        // collide with whatever Steam still thinks is registered for this
        // appID (the C++ side may not have fully released the slots).
    }

    public static bool IsInitialized => _initialized;

    // No struct constraint — see NativeCallbackRegistry.Register for
    // why some Steamworks callback types are classes under IL2Cpp interop.
    private static int TryRegister<T>(int callbackId, Action<T> handler, out IntPtr handle, string label, int sizeOverride = 0)
    {
        handle = IntPtr.Zero;
        try
        {
            handle = NativeCallbackRegistry.Register<T>(callbackId, handler, label, sizeOverride);
            return 1;
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"[SteamCallbacks] {label}: registration failed — {ex.GetType().Name}: {ex.Message}");
            return 0;
        }
    }

    // ────────────────────────────────────────────────────────────────────────
    //  Manual byte decode for SteamNetConnectionStatusChangedCallback_t
    // ────────────────────────────────────────────────────────────────────────
    //
    //  Marshal.PtrToStructure can't handle the IL2Cpp shim type (string field
    //  inside m_szEndDebug + lack of layout info). Layout cross-checked against
    //  ValveSoftware/GameNetworkingSockets steamnetworkingtypes.h and current
    //  rlabrecque/SteamworksSDK headers. SDK uses #pragma pack(push, 8)
    //  (VALVE_CALLBACK_PACK_LARGE on Windows), and m_info contains a uint64
    //  (m_nUserData) so the struct itself has 8-byte alignment requirement —
    //  4 bytes of padding sit between m_hConn (offset 0..3) and m_info (offset
    //  8..). Recent SDK additions m_idPOPRemote / m_idPOPRelay live between
    //  m_addrRemote and m_eState; without them in your layout chart all the
    //  later offsets shift by 4–8 bytes.
    //
    //    offset 0    HSteamNetConnection                  m_hConn          uint32 (4 bytes)
    //    offset 4    pad to 8                                              4 bytes
    //    offset 8    SteamNetConnectionInfo_t             m_info           696 bytes
    //                ├ 0   SteamNetworkingIdentity        m_identityRemote 136 bytes (pack(1) inside)
    //                │     ├ 0   ESteamNetworkingIdentityType m_eType      int  (4)
    //                │     ├ 4   int                          m_cbSize     int  (4) (=16 for SteamID identities)
    //                │     └ 8   union { uint64 m_steamID64; … }           up to 128 bytes
    //                │           (for SteamID type, m_steamID64 = first 8 bytes here)
    //                ├ 136 int64                          m_nUserData      8
    //                ├ 144 HSteamListenSocket             m_hListenSocket  4 ← we read this
    //                ├ 148 SteamNetworkingIPAddr          m_addrRemote     18
    //                ├ 166 uint16                         m__pad1          2
    //                ├ 168 uint32                         m_idPOPRemote    4
    //                ├ 172 uint32                         m_idPOPRelay     4
    //                ├ 176 ESteamNetworkingConnectionState m_eState        4 ← we read this
    //                ├ 180 int                            m_eEndReason     4
    //                ├ 184 char[128]                      m_szEndDebug     128 ← we read this
    //                ├ 312 char[128]                      m_szConnDescription 128
    //                ├ 440 uint32                         m_nFlags         4
    //                └ 444 uint32 reserved[63]                             252
    //    offset 704  ESteamNetworkingConnectionState      m_eOldState      int (4)
    //    total: 708 bytes
    //
    //  Absolute parent-struct offsets:
    //    m_hConn                                     0
    //    m_info.m_identityRemote.m_steamID64         8 + 8         =  16
    //    m_info.m_hListenSocket                      8 + 144       = 152
    //    m_info.m_eState                             8 + 176       = 184
    //    m_info.m_szEndDebug (128 bytes, NUL-term)   8 + 184       = 192
    //    m_eOldState                                 8 + 696       = 704
    //
    //  Size we report to Steam: 720 bytes (rounded up safely from 708).
    //
    //  Sanity check: at parent offset 12 (= m_info offset 4 = identity offset 4)
    //  is m_cbSize. For SteamID-type identities Steam fills it with 16. The
    //  hex-dump diagnostic in DecodeConnStatusAndDispatch lets us verify that
    //  in the live log without restoring a build.
    //
    private const int CONN_STATUS_SIZE        = 720;
    private const int OFF_HCONN               = 0;
    private const int OFF_STEAMID64           = 16;
    private const int OFF_HLISTENSOCKET       = 152;
    private const int OFF_ESTATE              = 184;
    private const int OFF_SZENDDEBUG          = 192;
    private const int OFF_EOLDSTATE           = 704;
    private const int LEN_SZENDDEBUG          = 128;

    private static int TryRegisterConnStatus()
    {
        try
        {
            _hConnStatusChanged = NativeCallbackRegistry.RegisterRaw(
                SteamNetConnectionStatusChangedCallback_t.k_iCallback,
                CONN_STATUS_SIZE,
                DecodeConnStatusAndDispatch,
                "SteamNetConnectionStatusChanged");
            return 1;
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"[SteamCallbacks] SteamNetConnectionStatusChanged: registration failed — {ex.GetType().Name}: {ex.Message}");
            _hConnStatusChanged = IntPtr.Zero;
            return 0;
        }
    }

    private static unsafe void DecodeConnStatusAndDispatch(IntPtr ptr)
    {
        if (ptr == IntPtr.Zero) return;
        byte* p = (byte*)ptr;

        uint  hConn         = *(uint*) (p + OFF_HCONN);
        ulong steamId64     = *(ulong*)(p + OFF_STEAMID64);
        uint  hListenSocket = *(uint*) (p + OFF_HLISTENSOCKET);
        int   eStateRaw     = *(int*)  (p + OFF_ESTATE);
        int   eOldStateRaw  = *(int*)  (p + OFF_EOLDSTATE);

        // Hex-dump first 160 bytes (covers identity + nUserData + hListenSocket
        // + addrRemote per agent's layout). Also scan for the expected SteamID
        // pattern so we don't have to eyeball it. Will remove once stable.
        try
        {
            var sb = new System.Text.StringBuilder(512);
            sb.Append("[ConnStatus][hex]");
            for (int i = 0; i < 160; i++)
            {
                if ((i & 31) == 0) sb.Append($"\n  +{i:D3}: ");
                sb.Append(((byte)*(p + i)).ToString("X2")).Append(' ');
            }
            Plugin.Log.LogInfo(sb.ToString());

            // Brute-force scan: look for any 8-byte sequence that decodes as
            // a high-bit-set Steam ID (0x011000010000_0000 .. 0x011000FFFFFF_FFFF
            // covers individual-account SteamIDs). If found, log offset.
            for (int off = 0; off + 8 <= 160; off += 4)
            {
                ulong v = *(ulong*)(p + off);
                // Steam individual SteamIDs are 0x0110000100000000 + accountID,
                // so the high 16 bits are 0x0110.
                if ((v >> 48) == 0x0110UL)
                {
                    Plugin.Log.LogInfo($"[ConnStatus][hex] candidate SteamID @ offset {off}: {v}");
                }
            }
        }
        catch { }

        // m_szEndDebug: ASCII null-terminated up to 128 bytes.
        string endDebug = "";
        for (int i = 0; i < LEN_SZENDDEBUG; i++)
        {
            byte b = *(p + OFF_SZENDDEBUG + i);
            if (b == 0)
            {
                endDebug = i == 0 ? "" : System.Text.Encoding.ASCII.GetString(p + OFF_SZENDDEBUG, i);
                break;
            }
            if (i == LEN_SZENDDEBUG - 1)
            {
                // Not null-terminated within the buffer — take the whole thing.
                endDebug = System.Text.Encoding.ASCII.GetString(p + OFF_SZENDDEBUG, LEN_SZENDDEBUG);
            }
        }

        // Diagnostic: every conn-status fire goes through here. If field
        // offsets are wrong we'll see clearly-bogus state values and can
        // adjust. Once stable, drop to LogDebug or remove.
        try
        {
            Plugin.Log.LogInfo($"[ConnStatus] hConn={hConn} remote={steamId64} listenSock={hListenSocket} {eOldStateRaw}→{eStateRaw} endDebug='{endDebug}'");
        }
        catch { }

        SteamTransport.OnConnectionStatusChanged(hConn, steamId64, hListenSocket, eOldStateRaw, eStateRaw, endDebug);
    }
}
