using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SoDCoop.Generators;

/// <summary>
/// Roslyn source generator that emits <c>Serialize(NetDataWriter)</c> /
/// <c>Deserialize(NetDataReader)</c> methods for partial structs marked
/// with <c>[NetPacket]</c>. Walks the public instance fields in
/// declaration order and emits the appropriate Put/Get calls.
///
/// <para><b>Why:</b> the manual NetSerializer.cs has 50+ packet structs
/// each with hand-written Serialize/Deserialize. Adding a field means
/// updating two methods consistently — easy to forget, source of subtle
/// bugs (round-trip mismatch / corrupt deserialization). This generator
/// makes the boilerplate automatic and keeps the wire format derivable
/// from the field declarations.</para>
///
/// <para><b>Supported field types:</b></para>
/// <list type="bullet">
///   <item><c>byte / sbyte / short / ushort / int / uint / long / ulong / float / double / bool</c></item>
///   <item><c>string</c> — null-coalesced to "" before Put.</item>
///   <item><c>byte[]</c> — length-prefixed.</item>
///   <item><c>UnityEngine.Vector3</c>, <c>Vector3Int</c>, <c>Quaternion</c></item>
/// </list>
///
/// <para>Unsupported types fall through with a compile-time diagnostic so
/// they're caught early. To convert an existing manually-serialized
/// packet: mark it <c>partial</c>, add <c>[NetPacket]</c>, delete the
/// hand-written methods. Generator emits them in a partial. The
/// generated file lives in <c>obj/Debug/...</c> at build time.</para>
/// </summary>
[Generator]
public class NetPacketGenerator : IIncrementalGenerator
{
    private const string AttrFullName = "SoDCoop.Network.NetPacketAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttrFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static s => s is not null);

        context.RegisterSourceOutput(packets, GenerateForType);
    }

    private static void GenerateForType(SourceProductionContext spc, INamedTypeSymbol type)
    {
        if (type is null) return;

        var ns      = type.ContainingNamespace?.ToDisplayString() ?? "";
        var name    = type.Name;
        var fields  = type.GetMembers().OfType<IFieldSymbol>()
                                       .Where(f => !f.IsStatic && !f.IsConst && f.DeclaredAccessibility == Accessibility.Public)
                                       .ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> — do not edit; regenerated from [NetPacket] field set.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using LiteNetLib.Utils;");
        sb.AppendLine("using UnityEngine;");
        if (!string.IsNullOrEmpty(ns)) sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"partial struct {name}");
        sb.AppendLine("{");

        // Serialize
        sb.AppendLine("    public void Serialize(NetDataWriter w)");
        sb.AppendLine("    {");
        foreach (var f in fields) EmitWrite(sb, f, spc);
        sb.AppendLine("    }");
        sb.AppendLine();

        // Deserialize
        sb.AppendLine("    public void Deserialize(NetDataReader r)");
        sb.AppendLine("    {");
        foreach (var f in fields) EmitRead(sb, f, spc);
        sb.AppendLine("    }");

        sb.AppendLine("}");

        spc.AddSource($"{name}.NetPacket.g.cs", sb.ToString());
    }

    private static void EmitWrite(StringBuilder sb, IFieldSymbol f, SourceProductionContext spc)
    {
        var t = f.Type.ToDisplayString();
        var n = f.Name;
        switch (t)
        {
            case "byte": case "sbyte":
            case "short": case "ushort":
            case "int": case "uint":
            case "long": case "ulong":
            case "float": case "double": case "bool":
                sb.AppendLine($"        w.Put({n});"); break;
            case "string":
                sb.AppendLine($"        w.Put({n} ?? \"\");"); break;
            case "byte[]":
                sb.AppendLine($"        w.Put({n}?.Length ?? 0);");
                sb.AppendLine($"        if ({n} != null && {n}.Length > 0) w.Put({n}, 0, {n}.Length);");
                break;
            case "UnityEngine.Vector3":
                sb.AppendLine($"        w.Put({n}.x); w.Put({n}.y); w.Put({n}.z);"); break;
            case "UnityEngine.Vector3Int":
                sb.AppendLine($"        w.Put({n}.x); w.Put({n}.y); w.Put({n}.z);"); break;
            case "UnityEngine.Quaternion":
                sb.AppendLine($"        w.Put({n}.x); w.Put({n}.y); w.Put({n}.z); w.Put({n}.w);"); break;
            default:
                ReportUnsupported(spc, f, t);
                sb.AppendLine($"        // [NetPacket] generator: skipping unsupported field {n} ({t})");
                break;
        }
    }

    private static void EmitRead(StringBuilder sb, IFieldSymbol f, SourceProductionContext spc)
    {
        var t = f.Type.ToDisplayString();
        var n = f.Name;
        switch (t)
        {
            case "byte":   sb.AppendLine($"        {n} = r.GetByte();"); break;
            case "sbyte":  sb.AppendLine($"        {n} = r.GetSByte();"); break;
            case "short":  sb.AppendLine($"        {n} = r.GetShort();"); break;
            case "ushort": sb.AppendLine($"        {n} = r.GetUShort();"); break;
            case "int":    sb.AppendLine($"        {n} = r.GetInt();"); break;
            case "uint":   sb.AppendLine($"        {n} = r.GetUInt();"); break;
            case "long":   sb.AppendLine($"        {n} = r.GetLong();"); break;
            case "ulong":  sb.AppendLine($"        {n} = r.GetULong();"); break;
            case "float":  sb.AppendLine($"        {n} = r.GetFloat();"); break;
            case "double": sb.AppendLine($"        {n} = r.GetDouble();"); break;
            case "bool":   sb.AppendLine($"        {n} = r.GetBool();"); break;
            case "string": sb.AppendLine($"        {n} = r.GetString();"); break;
            case "byte[]":
                sb.AppendLine($"        {{ int __len = r.GetInt(); {n} = new byte[__len]; for (int __i = 0; __i < __len; __i++) {n}[__i] = r.GetByte(); }}");
                break;
            case "UnityEngine.Vector3":
                sb.AppendLine($"        {{ float __x = r.GetFloat(), __y = r.GetFloat(), __z = r.GetFloat(); {n} = new Vector3(__x, __y, __z); }}");
                break;
            case "UnityEngine.Vector3Int":
                sb.AppendLine($"        {{ int __x = r.GetInt(), __y = r.GetInt(), __z = r.GetInt(); {n} = new Vector3Int(__x, __y, __z); }}");
                break;
            case "UnityEngine.Quaternion":
                sb.AppendLine($"        {{ float __x = r.GetFloat(), __y = r.GetFloat(), __z = r.GetFloat(), __w = r.GetFloat(); {n} = new Quaternion(__x, __y, __z, __w); }}");
                break;
            default:
                sb.AppendLine($"        // [NetPacket] generator: skipping unsupported field {n} ({t})");
                break;
        }
    }

    private static readonly DiagnosticDescriptor UnsupportedFieldType = new(
        id: "NETPKT001",
        title: "Unsupported [NetPacket] field type",
        messageFormat: "Field '{0}' of type '{1}' has no NetPacket serializer rule. Add a case in NetPacketGenerator or use a primitive proxy.",
        category: "SoDCoop.NetPacket",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static void ReportUnsupported(SourceProductionContext spc, IFieldSymbol f, string typeName)
    {
        var loc = f.Locations.FirstOrDefault() ?? Location.None;
        spc.ReportDiagnostic(Diagnostic.Create(UnsupportedFieldType, loc, f.Name, typeName));
    }
}
